identityRatio <- function(aln) {
    seqs <- sapply(aln$seqs[,2], strsplit, split="")
    sum(seqs[[1]] == seqs[[2]])/ aln$length
}

getIdx <- function(queryID, sourceID) {
    unlist(sapply(queryID, function(x) which(x == sourceID)))
}

pause <- function() {
    print("press ENTER to continue...")
    readline()
    invisible()
}

aln2seqDF <- function(aln) {
    seqs <- aln$seqs[,2]
    seq.df <- do.call("rbind", strsplit(seqs, ""))
    return(seq.df)
}

printFormatSeq <- function(seq, window=80) {
    jj <- seq(1, nchar(seq), window)
    if (jj[length(jj)] < nchar(seq)) {
        jj <- c(jj, nchar(seq))
    }
    for (p in 1:(length(jj)-1)) {
        cat(substring(seq, jj[p], jj[p+1]), "\n")
    }
}


addFooter <- function(file) {
    sink(file, append=TRUE)
    cat("\n")
    cat("## Info\n")
    cat("\nThis Report was generated by `skleid` version", as.character(packageVersion("skleid")),
        ".\nContact [Guangchuang](mailto:gcyu@connect.hku.hk) if you need helps.\n")
    sink() 
}
