identityRatio <- function(aln) {
    seqs <- sapply(aln$seqs[,2], strsplit, split="")
    sum(seqs[[1]] == seqs[[2]])/ aln$length
}

getIdx <- function(queryID, sourceID) {
    unlist(sapply(queryID, function(x) which(x == sourceID)))
}

pause <- function() {
    print("press ENTER to continue...")
    readline()
    invisible()
}

aln2seqDF <- function(aln) {
    seqs <- aln$seqs[,2]
    seq.df <- do.call("rbind", strsplit(seqs, ""))
    return(seq.df)
}

printFormatSeq <- function(seq, window=80) {
    jj <- seq(1, nchar(seq), window)
    if (jj[length(jj)] < nchar(seq)) {
        jj <- c(jj, nchar(seq))
    }
    for (p in 1:(length(jj)-1)) {
        cat(substring(seq, jj[p], jj[p+1]), "\n")
    }
}


addFooter <- function(file) {
    sink(file, append=TRUE)
    cat("\n")
    cat("## Info\n")
    cat("\nThis Report was generated by `skleid` version", as.character(packageVersion("skleid")),
        ".\nContact [Guangchuang](mailto:gcyu@connect.hku.hk) if you need helps.\n")
    sink() 
}

##' print Info
##'
##' 
##' @title printInfo
##' @return NULL
##' @author ygc
##' @export
printInfo <- function() {
    cat('\n')
    cat('         /-S\n')
    cat('      /-|\n')
    cat('   /-|   \\-K\n')
    cat('  |  |\n')
    cat('  |   \\----L\n')
    cat('--|\n')
    cat('  |      /-E\n')
    cat('  |   /-|\n')
    cat('   \\-|   \\-I\n')
    cat('     |\n')
    cat('      \\----D\n')  
    
    cat("\n###################################################################\n")
    cat("##\t\t\t\t\t\t\t\t ##\n")
    cat("##\t\t\t\t\t\t\t\t ##\n")
    cat('##  Author: Guangchuang Yu (gcyu@connect.hku.hk)\t\t ##\n')
    cat(paste('##  skleid package, version = ',
              as.character(packageVersion("skleid")), sep=""),
        "\t\t\t\t ##\n")
    cat('##  use help(package="skleid") to view online manuals\t\t ##\n') 
    cat('##  This package is designed for internal use of SKLEID lab\t ##\n')
    cat('##  If you got any problem, please contact me by email\t\t ##\n')
    cat("##\t\t\t\t\t\t\t\t ##\n")
    cat("##\t\t\t\t\t\t\t\t ##\n")
    cat("###################################################################\n\n")
}

getFiles <- function(path) {
    ff <- list.files(path=path)
    ff <- paste(path, ff, sep="/")
    return(ff)
}

moveUnknownFile <- function(contig.folder) {
    contig <- getFiles(contig.folder)
    sc <- getSampleID(contig)
    idx <- which(sc == contig)
    if (length(idx) >= 1) {
        moveFile(contig[idx], contig.folder, "unknown")
    }
}

moveFile <- function(files, from, to) {
    if (!file.exists(to))
        dir.create(to)
    for (ff in files) {
        file.rename(ff, to=sub(from, to, ff))
    }
}

moveEmptyFile <- function(folder) {
    ff <- getFiles(folder)
    ii <- which(file.info(ff)$size == 0)
    if (length(ii) > 0) {
        moveFile(ff[ii], folder, "empty")
    }
}

getMixedFileIndex <- function(files) {
    which(sapply(files, isMixed))
}


isMixed <- function(file) {
    ## prot <- gsub(pattern=".*/[^SRL]*[SRL]+\\d+(\\w+\\d*)_454.*", replacement="\\1", file)
    prot <- gsub(".*/.*_[SRL]+\\d+([HNMP][APSB]\\d*)_.*", replacement="\\1", file)
    
    prot.cutoff <- c(rep(2000, 4), 1000, rep(3000, 3))
    names(prot.cutoff) <- c("HA", "NA", "MP", "NP", "NS", "PA", "PB1", "PB2")
    
    res <- file.info(file)$size > prot.cutoff[prot]
    ## NDV that is not exists
    if (is.na(res))
        return(TRUE)
    return(res)
}

getSampleID <- function(contig) {
    sc <- gsub(".*/.*_([SRL]+\\d+)[HNMP]+.*", replacement="\\1", contig)
    return(sc)
}


moveMixedFile <- function(contig.folder) {
    contig <- getFiles(contig.folder)
    f454 <- contig[grep("_454.fa[sta]$", contig)]
    sc <- getSampleID(contig)
    idx <- getMixedFileIndex(f454)
    
    mix <- unique(gsub(pattern=".*/.*_([SRL]+\\d+)[HNMP][APSB]\\d*_.*", replacement="\\1", f454[idx]))
        
    if (length(mix) >= 1) {
        if (!file.exists("mixed"))
            dir.create("mixed")

        ii <- which(sc %in% mix)
        moveFile(contig[ii], contig.folder, "mixed")
    }

}

getMixedStrain <- function() {
    mix.sc <- NULL
    if (file.exists("mixed")) {
        mix <- getFiles("mixed")
        if (length(mix) > 0)
            mix.sc <- getSampleID(mix)
        if (length(mix.sc) == 0)
            mix.sc <- NULL
    }
    return(mix.sc)
}

moveNDVFile <- function(contig.folder) {
    ## S38-Yellow-CK-JX-10226-2014_S38NDV_454.fas
    ## S38-Yellow-CK-JX-10226-2014_S38NDV_Contigs.fna
    ## S38-Yellow-CK-JX-10226-2014_S38NDV_mira_delX.fasta
    ## S38-Yellow-CK-JX-10226-2014_S38NDV_mira.fasta
    contig <- getFiles(contig.folder)
    
    idx <- grep(".*/*_[SRL]+\\d+NDV_.*", contig)
    
    if (length(idx) >= 1) {
        if (!file.exists("NDV"))
            dir.create("NDV")
        moveFile(contig[idx], contig.folder, "NDV")
    }
}

